### ISSUE TITLE
Support for tab key

### ISSUE THREAD

**Issue by jacobuid** [joshsalverda/datepickr#8]
When the input is currently focused and the datepickr calendar is visible, and you press tab, the datepickr calendar stays open and another one opens showing 2 on the page.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/1899414/7032376/f7165394-dd37-11e4-99bf-c22ab4e8ca66.png)

**Comment by jacobuid** [comment]
**Here is the fix:**

Create new var:
![image](https://cloud.githubusercontent.com/assets/1899414/7032834/13c9e34a-dd3b-11e4-8ad4-49ca16635de3.png)

Assign this function here:
![image](https://cloud.githubusercontent.com/assets/1899414/7032817/ebfae06c-dd3a-11e4-9612-cad4a8dab131.png)

Add these eventListeners:
![image](https://cloud.githubusercontent.com/assets/1899414/7032823/01b245da-dd3b-11e4-9074-be1850dd4096.png)

**Comment by jacobuid** [comment]
If you want to add me as a collaborator, ill create a branch and a pull request for you to merge

**Comment by joshsalverda** [comment]
Nice, good call on the issue... I don't agree with your fix though :smiling_imp: Easier and more performant fix would be to add a blur event if the element is an input... something similar to the getOpenEvent method:

```
bindCloseMethod = function () {
    if (self.element.nodeName === 'INPUT') {
        self.addEventListener(self.element, 'blur', close, false);
    }
}
```

I can probably look at this later tonight... Or if you want you can submit a pull request by forking my repo, creating the branch on your fork, then submitting the pr back to my repo.

No offense, but I would prefer not to add you as a collaborator, I just don't know you all that well :smile:

**Comment by jacobuid** [comment]
Understood, i'm new to github, still finding my way around the site, i wasn't aware of the fork/pull request features. its all good! thanks for the added support!

**Comment by jacobuid** [comment]
@joshsalverda did you test your fix, it has introduced some new issues, just wanted to give you a heads up. i'm going to just proceed with a variation of my fix for now. thanks for the tech support.

**Comment by joshsalverda** [comment]
I did some quick tests, didn't fully test all functionality (really need to refactor my code so I can write proper unit tests)... thanks for checking, what issues are you noticing?

**Comment by jacobuid** [comment]
if you click the left(<) and right(>) calendar navigator buttons the datepickr calendar closes
